annotations:
  category: Redis Operator
appVersion: 4.3.1
apiVersion: v1
description: A Helm chart for the Power Home Redis Operator
name: redis-operator
version: 4.3.1
home: https://github.com/powerhome/redis-operator
keywords:
  - "golang"
  - "operator"
  - "cluster"
sources:
  - https://github.com/powerhome/redis-operator
kubeVersion: ">=1.21.0-0"
